package com.appsng.greendaoapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACTIVITY_TYPE".
*/
public class ActivityTypeDao extends AbstractDao<ActivityType, Long> {

    public static final String TABLENAME = "ACTIVITY_TYPE";

    /**
     * Properties of entity ActivityType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_activityType = new Property(1, Integer.class, "id_activityType", false, "ID_ACTIVITY_TYPE");
        public final static Property Title_activityType = new Property(2, String.class, "title_activityType", false, "TITLE_ACTIVITY_TYPE");
        public final static Property Row_version = new Property(3, String.class, "row_version", false, "ROW_VERSION");
    }

    private DaoSession daoSession;


    public ActivityTypeDao(DaoConfig config) {
        super(config);
    }
    
    public ActivityTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACTIVITY_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_ACTIVITY_TYPE\" INTEGER," + // 1: id_activityType
                "\"TITLE_ACTIVITY_TYPE\" TEXT," + // 2: title_activityType
                "\"ROW_VERSION\" TEXT);"); // 3: row_version
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACTIVITY_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ActivityType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer id_activityType = entity.getId_activityType();
        if (id_activityType != null) {
            stmt.bindLong(2, id_activityType);
        }
 
        String title_activityType = entity.getTitle_activityType();
        if (title_activityType != null) {
            stmt.bindString(3, title_activityType);
        }
 
        String row_version = entity.getRow_version();
        if (row_version != null) {
            stmt.bindString(4, row_version);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ActivityType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer id_activityType = entity.getId_activityType();
        if (id_activityType != null) {
            stmt.bindLong(2, id_activityType);
        }
 
        String title_activityType = entity.getTitle_activityType();
        if (title_activityType != null) {
            stmt.bindString(3, title_activityType);
        }
 
        String row_version = entity.getRow_version();
        if (row_version != null) {
            stmt.bindString(4, row_version);
        }
    }

    @Override
    protected final void attachEntity(ActivityType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ActivityType readEntity(Cursor cursor, int offset) {
        ActivityType entity = new ActivityType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // id_activityType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title_activityType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // row_version
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ActivityType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_activityType(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTitle_activityType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRow_version(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ActivityType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ActivityType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ActivityType entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
