package com.appsng.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ACTIVITY".
 */
@Entity
public class Activity {
//test
    @Id
    private Long id;
    private Integer id_activity;
    private String number_activity;
    private String title_activity;
    private String note_activity;
    private String row_version;
    private long id_lesson;
    private long id_activityType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Activity() {
    }

    public Activity(Long id) {
        this.id = id;
    }

    @Generated
    public Activity(Long id, Integer id_activity, String number_activity, String title_activity, String note_activity, String row_version, long id_lesson, long id_activityType) {
        this.id = id;
        this.id_activity = id_activity;
        this.number_activity = number_activity;
        this.title_activity = title_activity;
        this.note_activity = note_activity;
        this.row_version = row_version;
        this.id_lesson = id_lesson;
        this.id_activityType = id_activityType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getId_activity() {
        return id_activity;
    }

    public void setId_activity(Integer id_activity) {
        this.id_activity = id_activity;
    }

    public String getNumber_activity() {
        return number_activity;
    }

    public void setNumber_activity(String number_activity) {
        this.number_activity = number_activity;
    }

    public String getTitle_activity() {
        return title_activity;
    }

    public void setTitle_activity(String title_activity) {
        this.title_activity = title_activity;
    }

    public String getNote_activity() {
        return note_activity;
    }

    public void setNote_activity(String note_activity) {
        this.note_activity = note_activity;
    }

    public String getRow_version() {
        return row_version;
    }

    public void setRow_version(String row_version) {
        this.row_version = row_version;
    }

    public long getId_lesson() {
        return id_lesson;
    }

    public void setId_lesson(long id_lesson) {
        this.id_lesson = id_lesson;
    }

    public long getId_activityType() {
        return id_activityType;
    }

    public void setId_activityType(long id_activityType) {
        this.id_activityType = id_activityType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
