package com.appsng.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.appsng.greendaoapp.db.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ACTIVITY_TYPE".
 */
@Entity(active = true)
public class ActivityType {

    @Id
    private Long id;
    private Integer id_activityType;
    private String title_activityType;
    private String row_version;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ActivityTypeDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "id_activityType")
    })
    private List<Activity> all_activity;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ActivityType() {
    }

    public ActivityType(Long id) {
        this.id = id;
    }

    @Generated
    public ActivityType(Long id, Integer id_activityType, String title_activityType, String row_version) {
        this.id = id;
        this.id_activityType = id_activityType;
        this.title_activityType = title_activityType;
        this.row_version = row_version;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getActivityTypeDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getId_activityType() {
        return id_activityType;
    }

    public void setId_activityType(Integer id_activityType) {
        this.id_activityType = id_activityType;
    }

    public String getTitle_activityType() {
        return title_activityType;
    }

    public void setTitle_activityType(String title_activityType) {
        this.title_activityType = title_activityType;
    }

    public String getRow_version() {
        return row_version;
    }

    public void setRow_version(String row_version) {
        this.row_version = row_version;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Activity> getAll_activity() {
        if (all_activity == null) {
            __throwIfDetached();
            ActivityDao targetDao = daoSession.getActivityDao();
            List<Activity> all_activityNew = targetDao._queryActivityType_All_activity(id);
            synchronized (this) {
                if(all_activity == null) {
                    all_activity = all_activityNew;
                }
            }
        }
        return all_activity;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetAll_activity() {
        all_activity = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
