package com.appsng.greendaoapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.appsng.greendaoapp.db.Function;
import com.appsng.greendaoapp.db.Lesson;
import com.appsng.greendaoapp.db.Activity;
import com.appsng.greendaoapp.db.ActivityType;

import com.appsng.greendaoapp.db.FunctionDao;
import com.appsng.greendaoapp.db.LessonDao;
import com.appsng.greendaoapp.db.ActivityDao;
import com.appsng.greendaoapp.db.ActivityTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig functionDaoConfig;
    private final DaoConfig lessonDaoConfig;
    private final DaoConfig activityDaoConfig;
    private final DaoConfig activityTypeDaoConfig;

    private final FunctionDao functionDao;
    private final LessonDao lessonDao;
    private final ActivityDao activityDao;
    private final ActivityTypeDao activityTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        functionDaoConfig = daoConfigMap.get(FunctionDao.class).clone();
        functionDaoConfig.initIdentityScope(type);

        lessonDaoConfig = daoConfigMap.get(LessonDao.class).clone();
        lessonDaoConfig.initIdentityScope(type);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        activityTypeDaoConfig = daoConfigMap.get(ActivityTypeDao.class).clone();
        activityTypeDaoConfig.initIdentityScope(type);

        functionDao = new FunctionDao(functionDaoConfig, this);
        lessonDao = new LessonDao(lessonDaoConfig, this);
        activityDao = new ActivityDao(activityDaoConfig, this);
        activityTypeDao = new ActivityTypeDao(activityTypeDaoConfig, this);

        registerDao(Function.class, functionDao);
        registerDao(Lesson.class, lessonDao);
        registerDao(Activity.class, activityDao);
        registerDao(ActivityType.class, activityTypeDao);
    }
    
    public void clear() {
        functionDaoConfig.clearIdentityScope();
        lessonDaoConfig.clearIdentityScope();
        activityDaoConfig.clearIdentityScope();
        activityTypeDaoConfig.clearIdentityScope();
    }

    public FunctionDao getFunctionDao() {
        return functionDao;
    }

    public LessonDao getLessonDao() {
        return lessonDao;
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

    public ActivityTypeDao getActivityTypeDao() {
        return activityTypeDao;
    }

}
