package com.appsng.greendaoapp.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FUNCTION".
*/
public class FunctionDao extends AbstractDao<Function, Long> {

    public static final String TABLENAME = "FUNCTION";

    /**
     * Properties of entity Function.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Id_function = new Property(1, Integer.class, "id_function", false, "ID_FUNCTION");
        public final static Property Title_function = new Property(2, String.class, "title_function", false, "TITLE_FUNCTION");
        public final static Property Row_version = new Property(3, String.class, "row_version", false, "ROW_VERSION");
    }

    private DaoSession daoSession;


    public FunctionDao(DaoConfig config) {
        super(config);
    }
    
    public FunctionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FUNCTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_FUNCTION\" INTEGER," + // 1: id_function
                "\"TITLE_FUNCTION\" TEXT," + // 2: title_function
                "\"ROW_VERSION\" TEXT);"); // 3: row_version
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FUNCTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Function entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer id_function = entity.getId_function();
        if (id_function != null) {
            stmt.bindLong(2, id_function);
        }
 
        String title_function = entity.getTitle_function();
        if (title_function != null) {
            stmt.bindString(3, title_function);
        }
 
        String row_version = entity.getRow_version();
        if (row_version != null) {
            stmt.bindString(4, row_version);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Function entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer id_function = entity.getId_function();
        if (id_function != null) {
            stmt.bindLong(2, id_function);
        }
 
        String title_function = entity.getTitle_function();
        if (title_function != null) {
            stmt.bindString(3, title_function);
        }
 
        String row_version = entity.getRow_version();
        if (row_version != null) {
            stmt.bindString(4, row_version);
        }
    }

    @Override
    protected final void attachEntity(Function entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Function readEntity(Cursor cursor, int offset) {
        Function entity = new Function( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // id_function
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title_function
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // row_version
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Function entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId_function(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTitle_function(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRow_version(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Function entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Function entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Function entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
