package com.appsng.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.appsng.greendaoapp.db.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LESSON".
 */
@Entity(active = true)
public class Lesson {

    @Id
    private Long id;
    private Integer id_lesson;
    private String number_lesson;
    private String row_version;
    private long id_function;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient LessonDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "id_lesson")
    })
    private List<Activity> all_activity;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Lesson() {
    }

    public Lesson(Long id) {
        this.id = id;
    }

    @Generated
    public Lesson(Long id, Integer id_lesson, String number_lesson, String row_version, long id_function) {
        this.id = id;
        this.id_lesson = id_lesson;
        this.number_lesson = number_lesson;
        this.row_version = row_version;
        this.id_function = id_function;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLessonDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getId_lesson() {
        return id_lesson;
    }

    public void setId_lesson(Integer id_lesson) {
        this.id_lesson = id_lesson;
    }

    public String getNumber_lesson() {
        return number_lesson;
    }

    public void setNumber_lesson(String number_lesson) {
        this.number_lesson = number_lesson;
    }

    public String getRow_version() {
        return row_version;
    }

    public void setRow_version(String row_version) {
        this.row_version = row_version;
    }

    public long getId_function() {
        return id_function;
    }

    public void setId_function(long id_function) {
        this.id_function = id_function;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Activity> getAll_activity() {
        if (all_activity == null) {
            __throwIfDetached();
            ActivityDao targetDao = daoSession.getActivityDao();
            List<Activity> all_activityNew = targetDao._queryLesson_All_activity(id);
            synchronized (this) {
                if(all_activity == null) {
                    all_activity = all_activityNew;
                }
            }
        }
        return all_activity;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetAll_activity() {
        all_activity = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
